=== doc-ai/tensorio/schemas/v0.7.0/tensorflow/schema.json
{
  "$schema":  "http://json-schema.org/draft-07/schema#",
  "$id":      "https://github.com/doc-ai/tensorio/schemas/v0.7.0/tensorflow/schema.json",

  "definitions": {
    
    "model": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "file",
        "quantized"
      ],
      "properties": {
        "file":       { "type":   "string"      },
        "quantized":  { "type":   "boolean"     },
        "type":       { "type":   "string"      },
        "backend":    { "type":   "string",
                        "const":  "tensorflow"  },
        "class":      { "type":   "string"      },
        "modes":      {
          "type": "array",
           "items": {
            "type": "string",
            "enum": ["predict", "train"]
          }
        }
      }
    },

    "options": {
      "type": "object",
      "additionalProperties": true,
      "properties": {
        "device_position":  { "type": "string" },
        "output_format":    { "type": "string" }
      }
    },

    "input.array.quantize": {
      "type": "object",
      "oneOf": [
        {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "standard": { "type": "string" }
          }
        },
        {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "scale":    { "type": "number" },
            "bias":     { "type": "number" }
          }
        }
      ]
    },

    "input.array": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "name",
        "type",
        "shape"
      ],
      "properties": {
        "name": {
          "type": "string"
        },
        "type": {
          "type": "string",
          "enum": ["array"]
        },
        "dtype": {
          "type": "string",
          "enum": ["uint8, float32", "int32", "int64"]
        },
        "shape": {
          "type": "array",
          "items": { "type": "integer" }
        },
        "quantize": {
          "$ref": "#/definitions/input.array.quantize"
        }
      }
    },

    "input.image.normalize": {
      "type": "object",
      "oneOf": [
        {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "standard": { "type": "string" }
          }
        },
        {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "scale":    { "type": "number" },
            "bias": {
              "type": "object",
              "additionalProperties": false,
              "properties": {
                "r":    { "type": "number" },
                "g":    { "type": "number" },
                "b":    { "type": "number" }
              }
            }
          }
        }
      ]
    },

    "input.image": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "name",
        "type",
        "shape",
        "format"
      ],
      "properties": {
        "type": {
          "type": "string",
          "enum": ["image"]
        },
        "name": {
          "type": "string"
        },
        "shape": {
          "type": "array",
          "items": { "type": "integer" }
        },
        "format": {
          "type": "string",
          "enum": ["RGB", "BGR"]
        },
        "normalize": {
          "$ref": "#/definitions/input.image.normalize"
        }
      }
    },

    "output.array.dequantize": {
      "type": "object",
      "oneOf": [
        {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "standard": { "type": "string" }
          }
        },
        {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "scale":    { "type": "number" },
            "bias":     { "type": "number" }
          }
        }
      ]
    },

    "output.array": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "name",
        "type",
        "shape"
      ],
      "properties": {
        "name": {
          "type": "string"
        },
        "type": {
          "type": "string",
          "enum": ["array"]
        },
        "dtype": {
          "type": "string",
          "enum": ["uint8, float32", "int32", "int64"]
        },
        "shape": {
          "type": "array",
          "items": { "type": "integer" }
        },
        "labels": {
          "type": "string"
        },
        "dequantize": {
          "$ref": "#/definitions/output.array.dequantize"
        }
      }
    },

    "output.image.denormalize": {
      "type": "object",
      "oneOf": [
        {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "standard": { "type": "string" }
          }
        },
        {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "scale":    { "type": "number" },
            "bias": {
              "type": "object",
              "additionalProperties": false,
              "properties": {
                "r":    { "type": "number" },
                "g":    { "type": "number" },
                "b":    { "type": "number" }
              }
            }
          }
        }
      ]
    },

    "output.image": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "name",
        "type",
        "shape",
        "format"
      ],
      "properties": {
        "type": {
          "type": "string",
          "enum": ["image"]
        },
        "name": {
          "type": "string"
        },
        "shape": {
          "type": "array",
          "items": { "type": "integer" }
        },
        "format": {
          "type": "string",
          "enum": ["RGB", "BGR"]
        },
        "denormalize": {
          "$ref": "#/definitions/output.image.denormalize"
        }
      }
    },

    "train": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "ops"
      ],
      "properties": {
        "ops": { 
          "type": "array",
          "items": { "type": "string" }
        }
      }
    }

  },
  
  "type": "object",
  "additionalProperties": false,
  "required": [
    "name",
    "details",
    "id",
    "version",
    "author",
    "license",
    "model",
    "inputs",
    "outputs"
  ],
  "properties": {
    "name":         { "type": "string" },
    "details":      { "type": "string" },
    "id":           { "type": "string" },
    "version":      { "type": "string" },
    "author":       { "type": "string" },
    "license":      { "type": "string" },
    "placeholder":  { "type": "boolean" },
    "model":        { "$ref": "#/definitions/model" },
    "inputs": {
      "type": "array",
      "items": {
        "oneOf": [
          { "$ref": "#/definitions/input.array" },
          { "$ref": "#/definitions/input.image" }
        ]
      }
    },
    "outputs": {
      "type": "array",
      "items": {
        "oneOf": [
          { "$ref": "#/definitions/output.array" },
          { "$ref": "#/definitions/output.image" }
        ]
      }
    },
    "train":    { "$ref": "#/definitions/train"   },
    "options":  { "$ref": "#/definitions/options" }
  }
}

=== doc-ai/tensorio/schemas/v1.2.6/tensorflow/tests/valid/cats-vs-dogs-train.json
{
	"name": "Cats vs Dogs MobileNet V2 1.0 128",
	"details": "Cats vs Dogs Kaggle model based on MobileNet V2 architecture with a width multiplier of 1.0 and an input resolution of 128x128.",
	"id": "cats-vs-dogs-v2-100-128-unquantized",
	"version": "1",
	"author": "doc.ai",
	"license": "Apache License. Version 2.0 http://www.apache.org/licenses/LICENSE-2.0",
	"model": {
		"file": "train",
		"quantized": false,
		"type": "image.classification.catsvsdogs",
		"backend": "tensorflow",
		"modes": ["train"]
	},
	"inputs": [
		{
			"name": "image",
			"type": "image",
			"shape": [-1,128,128,3],
			"format": "RGB",
			"normalize": { "standard": "[0,1]" }
		},
		{
			"name": "labels",
			"type": "array",
			"dtype": "int32",
			"shape": [-1,1]
		}
	],
	"outputs": [
		{
			"name": "sigmoid_cross_entropy_loss/value",
			"type": "array",
			"shape": [1]
		}
	],
	"train": {
		"ops": [
			"train"
		]
	}
}

=== doc-ai/tensorio/schemas/v0.6.1/tensorflow/tests/valid/1_in_1_out_pixelbuffer_normalization_test.json
{
	"name": "1 in 1 out pixel buffer normalization test",
	"details": "Outputs the input pixel buffer but normalized to [-1,1] from [0,1]. Made to test the normalization and denormalization functions.",
	"id": "1_in_1_out_pixelbuffer_normalization_test",
	"version": "1",
	"author": "doc.ai",
	"license": "",
	"model": {
		"file": "predict",
		"quantized": false,
		"backend": "tensorflow"
	},
	"inputs": [
		{
			"name": "input",
			"type": "image",
			"shape": [224,224,3],
			"format": "RGB",
			"normalize": {
				"standard": "[0,1]"
			}
		}
	],
	"outputs": [
		{
			"name": "output",
			"type": "image",
			"shape": [224,224,3],
			"format": "RGB",
			"denormalize": {
				"standard": "[-1,1]"
			}
		}
	]
}

=== doc-ai/tensorio/schemas/v0.7.0/tensorflow/tests/valid/1_in_1_out_pixelbuffer_identity_test.json
{
	"name": "1 in 1 out pixel buffer identity test",
	"details": "Outputs the input pixel buffer. Made to test the normalization and denormalization functions.",
	"id": "1_in_1_out_pixelbuffer_identity_test",
	"version": "1",
	"author": "doc.ai",
	"license": "",
	"model": {
		"file": "predict",
		"quantized": false,
		"backend": "tensorflow",
		"modes": ["predict"]
	},
	"inputs": [
		{
			"name": "input",
			"type": "image",
			"shape": [224,224,3],
			"format": "RGB",
			"normalize": {
				"standard": "[0,1]"
			}
		}
	],
	"outputs": [
		{
			"name": "output",
			"type": "image",
			"shape": [224,224,3],
			"format": "RGB",
			"denormalize": {
				"standard": "[0,1]"
			}
		}
	]
}

=== doc-ai/tensorio/schemas/v0.7.0/tensorflow/tests/valid/cats-vs-dogs-predict.json
{
	"name": "Cats vs Dogs MobileNet V2 1.0 128",
	"details": "Cats vs Dogs Kaggle model based on MobileNet V2 architecture with a width multiplier of 1.0 and an input resolution of 128x128.",
	"id": "cats-vs-dogs-v2-100-128-unquantized",
	"version": "1",
	"author": "doc.ai",
	"license": "Apache License. Version 2.0 http://www.apache.org/licenses/LICENSE-2.0",
	"model": {
		"file": "predict",
		"quantized": false,
		"type": "image.classification.catsvsdogs",
		"backend": "tensorflow",
		"modes": ["predict"]
	},
	"inputs": [
		{
			"name": "image",
			"type": "image",
			"shape": [-1,128,128,3],
			"format": "RGB",
			"normalize": {
				"standard": "[0,1]"
			}
		}
	],
	"outputs": [
		{
			"name": "sigmoid",
			"type": "array",
			"shape": [-1,1],
			"labels": "labels.txt"
		}
	],
	"options": {
		"device_position": "back"
	}
}

=== doc-ai/tensorio/schemas/v1.2.4/tflite/tests/valid/placeholder.json
{
	"name": "Placeholder model",
	"details": "Bundle with no model file that should otherwise parse the json and instantiate an empty model.",
	"id": "placeholder_test",
	"version": "1",
	"author": "doc.ai",
	"license": "",
	"placeholder": true,
	"model": {
		"file": "",
		"quantized": false
	},
	"inputs": [
		{
			"name": "input_x",
			"type": "array",
			"shape": [1]
		}
	],
	"outputs": [
		{
			"name": "output_z",
			"type": "array",
			"shape": [1]
		}
	]
}
